# claude-jsqualityhooks.config.yaml
# Example configuration file

# Enable validation
enabled: true
autoFix: true

# Configure validators
validators:
  biome:
    enabled: true
    version: auto  # Auto-detects Biome version
  typescript: true

# Optional: Custom file patterns (has smart defaults)
# include:
#   - "src/**/*.{ts,tsx,js,jsx}"
# exclude:
#   - "node_modules/**"